#cloud-config
# AWS Cloud-Optimized Configuration

# Set hostname based on instance metadata
hostname: ${aws:instance-id}

# Update package sources for AWS regions
apt:
  sources:
    awscli:
      source: "deb [arch=amd64] https://awscli.amazonaws.com/awscli stable main"
      keyid: "FB5DB77FD5C118B80511ADA8A6310ACC4672475C"

# Install AWS-specific packages
packages:
  - awscli
  - amazon-ec2-utils
  - amazon-ssm-agent
  - cloud-guest-utils
  - ec2-instance-connect

# Configure AWS services
write_files:
  - path: /etc/awslogs/awslogs.conf
    content: |
      [general]
      state_file = /var/lib/awslogs/agent-state

      [/var/log/syslog]
      datetime_format = %b %d %H:%M:%S
      file = /var/log/syslog
      log_stream_name = {instance_id}
      log_group_name = /var/log/syslog

      [/var/log/cloud-init.log]
      datetime_format = %Y-%m-%d %H:%M:%S
      file = /var/log/cloud-init.log
      log_stream_name = {instance_id}
      log_group_name = /var/log/cloud-init.log

  - path: /etc/amazon/ssm/seelog.xml
    content: |
      <seelog type="adaptive" mininterval="2000000" maxinterval="100000000" critmsgcount="500" minlevel="info">
        <exceptions>
          <exception filepattern="test*" minlevel="error"/>
        </exceptions>
        <outputs formatid="fmtinfo">
          <console formatid="fmtinfo"/>
          <rollingfile type="size" filename="/var/log/amazon/ssm/amazon-ssm-agent.log" maxsize="30000000" maxrolls="5"/>
        </outputs>
        <formats>
          <format id="fmterror" format="%Date %Time %LEVEL [%FuncShort @ %File.%Line] %Msg%n"/>
          <format id="fmtinfo" format="%Date %Time %LEVEL %Msg%n"/>
        </formats>
      </seelog>

# Run commands on first boot
runcmd:
  - systemctl enable amazon-ssm-agent
  - systemctl start amazon-ssm-agent
  - /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource EC2Instance --region ${AWS::Region}

# Configure NTP for AWS
ntp:
  servers:
    - 169.254.169.123

# Mount EBS volumes
mounts:
  - [ /dev/xvdf, /data, ext4, "defaults,nofail", "0", "2" ]

# Configure SSH for AWS
ssh_authorized_keys:
  - ${aws:ec2-userdata}

# Final message
final_message: "Cloud-Optimized Linux Distribution booted on AWS - Instance: ${aws:instance-id}"
